// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltvfptppzflwgbcdeooz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0dmZwdHBwemZsd2diY2Rlb296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzc5ODksImV4cCI6MjA2OTkxMzk4OX0.OC-JjScryDUkQHD_RRY8ueo2PiG6-ruhUo6UEuTMWlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});